config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy], as: 'delete_bookmark'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :delete_all
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks


  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= render 'shared/navbar' %>
<div class='container mt-4'>
<h1>Add a new bookmark!</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit 'Add Bookmark', class: 'btn btn-primary'%>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render 'shared/navbar' %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/7081161/pexels-photo-7081161.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500);">
  <div class="container">
    <h1><strong>Le Wagon Movie List Directory</strong></h1>
    <p>Classic</p>
  </div>
</div>


<div class="container h1 mt-4">
<h3>Estas son las listas:</h3>
</div>


<div class="container boton mt-2">
<%= link_to 'Add a new list', new_list_path, class: 'btn btn-primary'%>
</div>



<div class="grid-container mt-5">
<% @lists.each do |list| %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>');">
<div class='categoria'>
<%= link_to list.name, list_path(list[:id]), class: 'link' %>
</div>
</div>
<% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
<h2>Create a new list</h2>
</div>

<div class="container">
<%= simple_form_for(@list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit "Create List", class: "btn btn-primary"%>
<% end %>
</div>

app/views/lists/show.html.erb
<%= render 'shared/navbar' %>

<%# Esto es el banner %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>');">
  <div class="container">
    <h1><strong><%= @list.name %></strong></h1>
  </div>
</div>

<%# Esto es el el add a bookmark btn %>
<div class="container h1">
<%= link_to "Add a bookmark", new_list_bookmark_path(@list) , class:"btn btn-primary"%>
</div>


<div class="card-group mt-4">
<%# Esta es la card  %>
<% @list.movies.each do |movie| %>
<div class="card" >
  <img src="https://media1.popsugar-assets.com/files/thumbor/7CwCuGAKxTrQ4wPyOBpKjSsd1JI/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2017/04/19/743/n/41542884/5429b59c8e78fbc4_MCDTITA_FE014_H_1_.JPG" class="card-img-top" alt="movie-image">
  <div class="card-body">
  <%# Este es el titulo de la película  %>
    <h5 class="card-title"> <strong><%= movie.title %></strong></h5>
    <%# Este es el overview de la película  %>
    <p class="card-text"><%= movie.overview %></p>
  </div>
  <ul class="list-group list-group-flush">
  <%# Este es el bookmark de la película  %>
   <% movie.bookmarks.each do |bookmark| %>
    <li class="list-group-item">
      <div class='d-flex justify-content-between'>
        <div><i class="fas fa-comment"></i> <%= bookmark.comment %></div>
        <%= link_to "Delete", delete_bookmark_path(bookmark), method: :delete, data: {confirm: 'Are you sure?'}, class:"delete" %>
      </div>
    </li>
  </ul>
</div>
<% end %>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <i class="fas fa-film"></i>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" <%= link_to "My Lists", lists_path(@lists), class: "btn btn-primary"%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">New List</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>